services:
  remix:
    container_name: remix
    build:
      context: .
      dockerfile: ./apps/remix/Dockerfile
    ports:
      - 3333:3333
    environment:
      API_URL: http://nestjs:2222
    depends_on:
      - nestjs
    networks:
      - app-network

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: ./apps/nestjs/Dockerfile
    ports:
      - 2222:2222
    environment:
      MONGO_URI: mongodb://mongo:27017/db
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
