# fly.toml app configuration file generated for pnpm-monorepo-remix on 2023-11-25T04:34:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pnpm-monorepo-remix"
primary_region = "waw"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
